version: '3.1'

services:

  redmine_test1_db:
    image: postgres:12.2-alpine
    container_name: redmine_test1_db
    restart: always
  #   ports:
  #     - 5444:5432
  #   volumes:
  #   - /home/gocp/redmine/test1-redmine/data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: redmine
  #     # (variable 미지정시 postgres)
  #     POSTGRES_USER: redmine
  #     POSTGRES_PASSWORD: passwd

  # redmine_test1:
  #   image: redmine:4.1-passenger
  #   restart: always
  #   container_name: redmine_test1_container
  #   ports:
  #     - 7270:3000
  #   volumes:
  #     - /home/gocp/redmine/test1-redmine/files:/usr/src/redmine/files
  #     - /home/gocp/redmine/test1-redmine/themes:/usr/src/redmine/public/themes
  #     - /home/gocp/redmine/test1-redmine/plugins:/usr/src/redmine/plugins
  #   environment:
  #     # 연결할 디비 서비스명 (variable 미지정시 SQlite)
  #     REDMINE_DB_POSTGRES: redmine_test1_db
  #     REDMINE_DB_USERNAME: redmine
  #     REDMINE_DB_DATABASE: redmine
  #     REDMINE_DB_PASSWORD: passwd
